name: Build and Release LaTeX Document

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build on
  workflow_dispatch:  # Allows manual triggering


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up LaTeX environment
      uses: xu-cheng/latex-action@v2
      with:
        root_file: khaled_sde_resume.tex  # Change this to the name of your main LaTeX file
        compiler: pdflatex

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert LaTeX to Word
      run: pandoc khaled_sde_resume.tex -s -o khaled_sde_resume.docx
      # Ensure 'khaled_sde_resume.tex' is the name of your LaTeX file

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # Change this to the desired tag name
        release_name: Resume v1.0.0  # Change this to the desired release name
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: khaled_sde_resume.pdf  # Change this to the path of your PDF file
        asset_name: khaled_sde_resume.pdf  # Change this to the desired name of the asset
        asset_content_type: application/pdf

    - name: Upload DOCX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: khaled_sde_resume.docx  # Change this to the path of your DOCX file
        asset_name: khaled_sde_resume.docx  # Change this to the desired name of the asset
        asset_content_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
